config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :books
  resources :authors
  root 'home#index'

  devise_for :users

  resource :authors
  resource :books

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates_uniqueness_of :name
  validates_presence_of :name, :dob
  self.per_page = 5

  def age
    Time.now.year - self.dob.year
  end

  def new_attribute
    {
      id: self.id,
      name: self.name,
      dob: self.dob,
      age: self.age,
      books: self.books.map do |book|
        {
          id: book.id,
          title: book.title,
          genre: book.genre,
          released_date: book.released_date,
          language: book.language
        }
      end
    }
  end

  def self.search_attribute data
    {
      data: data,
      pagination: {
        current_page: data.current_page,
        total_pages: data.total_pages,
        total_items: data.total_entries
      }
    }
  end

  def self.search(query, page, per_page, sort_by, sort_direction)
    authors = self.where("name like ?", "%#{query}%")
    authors = authors.order("#{sort_by} #{sort_direction}") if sort_by.present? && sort_direction.present?
    authors.paginate(page: page, per_page: per_page)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]
  before_action :authenticate_user, except: [:index, :show]

  # GET /authors or /authors.json
  def index
    @authors = Author.search(
      search_params[:query],
      search_params[:page],
      search_params[:per_page],
      search_params[:sort_by],
      search_params[:sort_direction]
    ).paginate(page: params[:page], per_page: params[:per_page])
    respond_to do |format|
      format.json {  render json: Author.search_attribute(@authors) }
      format.html { @authors = @authors }
    end
  end

  # GET /authors/1 or /authors/1.json
  def show
    respond_to do |format|
      format.json {  render json: @author.new_attribute }
      format.html { @author }
    end
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :dob)
    end

    def search_params
      params.permit(:query, :page, :per_page, :sort_by, :sort_direction)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>" class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><strong>Name:</strong> <%= author.name %></h5>
    <p class="card-text"><strong>Age:</strong> <%= author.age %></p>
    <% if action_name != 'show' %>
      <p class="card-link">
        <%= link_to "Show this author", author, class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, class: 'needs-validation', novalidate: true) do |form| %>
  <% if author.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :dob %>
    <%= form.date_field :dob, class: 'form-control', required: true %>
  </div>

  <div class="form-group mt-4">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author, class: "btn btn-primary" %> |
  <%= link_to "Back to authors", authors_path, class: "btn btn-secondary" %>
</div>

app/views/authors/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1 class="mt-4">Authors</h1>
  <%= link_to "New Author", new_author_path, class: "btn btn-primary" %>
</div>

<div id="filters" class="mt-4">
  <form class="form-inline d-flex mb-2" method="get">
    <div class="form-group mr-2">
      <input type="text" class="form-control" name="query" placeholder="Search by name" value="<%= params[:query] %>">
    </div>
    <div class="form-group mr-2">
      <select class="form-control" name="per_page">
        <option value="5" <%= 'selected' if params[:per_page] == '5' %>>5 per page</option>
        <option value="10" <%= 'selected' if params[:per_page] == '10' %>>10 per page</option>
        <option value="20" <%= 'selected' if params[:per_page] == '20' %>>20 per page</option>
        <option value="30" <%= 'selected' if params[:per_page] == '30' %>>30 per page</option>
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Apply Filters</button>
  </form>
</div>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <hr />
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @authors, params: { query: params[:query], per_page: params[:per_page] } %>
  </div>
</div>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path, class: "btn btn-secondary" %>
</div>

app/views/authors/show.html.erb
<div class="container">
  <p class="alert alert-success"><%= notice %></p>

  <%= render @author %>

  <div class="mt-3">
    <%= link_to "Back to authors", authors_path, class: "btn btn-secondary mr-2 mb-2" %>
    <%= link_to "Edit this author", edit_author_path(@author), class: "btn btn-primary mr-2 mb-2" %>
    <%= button_to "Destroy this author", @author, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>