config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :books
  resources :authors
  root 'home#index'

  devise_for :users

  resource :authors
  resource :books

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  validates_presence_of :title, :author_id, :released_date, :genre, :language
  self.per_page = 5

  def self.search_attribute data
    {
      data: data.map(&:new_attribute),
      pagination: {
        current_page: data.current_page,
        total_pages: data.total_pages,
        total_items: data.total_entries
      }
    }
  end

  def new_attribute
    {
      id: self.id,
      title: self.title,
      genre: self.genre,
      author: {
        name: self.author.name,
        age: self.author.age
      },
      released_date: self.released_date,
      language: self.language
    }
  end
  def self.search(query, page, per_page, min_realised_date, max_realised_date, language, sort_by, sort_direction)
    books = Book.joins(:author).where("authors.name LIKE :query OR books.title LIKE :query", query: "%#{query}%")
    books = books.where("released_date >= ?", min_realised_date) if min_realised_date.present?
    books = books.where("released_date <= ?", max_realised_date) if max_realised_date.present?
    books = books.where("language = ?", language) if language.present?
    books = books.order("#{sort_by} #{sort_direction}") if sort_by.present? && sort_direction.present?
    books.paginate(page: page, per_page: per_page)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user, except: [:index, :show]

  # GET /books or /books.json
  def index
    @books = Book.search(
      search_params[:query],
      search_params[:page],
      search_params[:per_page],
      search_params[:min_realised_date],
      search_params[:max_realised_date],
      search_params[:language],
      search_params[:sort_by],
      search_params[:sort_direction]
    ).paginate(page: params[:page], per_page: params[:per_page])

    respond_to do |format|
      format.json { render json: Book.search_attribute(@books) }
      format.html { @books = @books }
    end
  end

  # GET /books/1 or /books/1.json
  def show
    respond_to do |format|
      format.json { render json: @book.new_attribute }
      format.html { @book }
    end
  end

  # GET /books/new
  def new
    @book = Book.new
    @authors = Author.all
  end

  # GET /books/1/edit
  def edit
    @authors = Author.all
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        MailerJob.perform_async(current_user.id, @book.id)
        format.html { redirect_to books_url, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author_id, :released_date, :genre, :language)
    end

    def search_params
      params.permit(:query, :page, :per_page, :min_realised_date, :max_realised_date, :language, :sort_by, :sort_direction)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <table class="table table-bordered">
    <tr>
      <th>Title</th>
      <td><%= book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= book.author.name %></td>
    </tr>
    <tr>
      <th>Released Date</th>
      <td><%= book.released_date %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= book.genre %></td>
    </tr>
    <tr>
      <th>Language</th>
      <td><%= book.language %></td>
    </tr>
  </table>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, class: "form") do |form| %>
  <% if book.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, @authors, :id, :name, { prompt: 'Select an author' }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :released_date %>
    <%= form.date_field :released_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :language %>
    <%= form.text_field :language, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book, class: "btn btn-primary" %> |
  <%= link_to "Back to books", books_path, class: "btn btn-secondary" %>
</div>

app/views/books/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1 class="mt-4">Books</h1>
  <%= link_to "New Book", new_book_path, class: "btn btn-primary" %>
</div>

<div id="filters" class="mt-4">
  <form class="form-inline d-flex mb-2" method="get">
    <div class="form-group mr-2">
      <input type="text" class="form-control" name="query" placeholder="Search by title or author" value="<%= params[:query] %>">
    </div>
    <div class="form-group mr-2">
      <select class="form-control" name="per_page">
        <option value="5" <%= 'selected' if params[:per_page] == '5' %>>5 per page</option>
        <option value="10" <%= 'selected' if params[:per_page] == '10' %>>10 per page</option>
        <option value="20" <%= 'selected' if params[:per_page] == '20' %>>20 per page</option>
        <option value="30" <%= 'selected' if params[:per_page] == '30' %>>30 per page</option>
      </select>
    </div>
    <div class="form-group mr-2">
      <input type="date" class="form-control" name="min_realised_date" placeholder="Min Release Date" value="<%= params[:min_realised_date] %>">
    </div>
    <div class="form-group mr-2">
      <input type="date" class="form-control" name="max_realised_date" placeholder="Max Release Date" value="<%= params[:max_realised_date] %>">
    </div>
    <div class="form-group mr-2">
      <select class="form-control" name="sort_by">
        <option value="title" <%= 'selected' if params[:sort_by] == 'title' %>>Title</option>
        <option value="released_date" <%= 'selected' if params[:sort_by] == 'released_date' %>>Release Date</option>
        <option value="author_id" <%= 'selected' if params[:sort_by] == 'author_id' %>>Author</option>
      </select>
    </div>
    <div class="form-group mr-2">
      <select class="form-control" name="sort_direction">
        <option value="asc" <%= 'selected' if params[:sort_direction] == 'asc' %>>Ascending</option>
        <option value="desc" <%= 'selected' if params[:sort_direction] == 'desc' %>>Descending</option>
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Apply Filters</button>
  </form>
</div>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book, class: "btn btn-primary" %>
    </p>
    <hr />
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @books, params: { query: params[:query], per_page: params[:per_page], min_realised_date: params[:min_realised_date], max_realised_date: params[:max_realised_date], sort_by: params[:sort_by], sort_direction: params[:sort_direction] } %>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book), class: "btn btn-primary mr-2 mb-2" %> |
  <%= link_to "Back to books", books_path, class: "btn btn-secondary mr-2 mb-2" %>

  <%= button_to "Destroy this book", @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>